### ISSUE TITLE
Version 1.0.48 ignores setting metrics-server deploy to false

### ISSUE THREAD

**Issue by ahoward-conga** [spotinst/spotinst-kubernetes-helm-charts#15]
When deploying version 1.0.48 of the chart, setting
```
metrics-server:
  deployChart: false
```
will deploy metrics-server into the cluster anyway.

**Comment by ghost** [comment]
@liranp This bug was re-introduced.
In https://github.com/spotinst/spotinst-kubernetes-helm-charts/commit/88aca9cab7991129a4d4d3391e10d86e652176c7 you removed the `dependencies` block.

And then it was added back in by @yeminiori in:
https://github.com/spotinst/spotinst-kubernetes-helm-charts/commit/9a67c944758d9b4f0e14e8dce749b7181ed6e56a#diff-43a27642790006c93fea79f384f23b4f
